

version: "3.8"

services: 
  www:
    build:
      context: ./dockerfiles
      dockerfile: www.dockerfile
    container_name: bidc_php_apache
    image: php7.4_apache
    volumes: 
      # - D:\Project_Space\PHP_mars_Project_utf8\Manage\okems:/var/www/html/okems   #프로젝트 경로(로컬경로:도커안의경로)
      - ./Project:/var/www/html/okems   #프로젝트 경로(로컬경로:도커안의경로)

      - ./config/php/php_7.4.ini:/usr/local/etc/php/php.ini
      - ./config/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./config/apache2/httpd-vhost.conf:/etc/apache2/sites-enabled/httpd-vhost.conf
    ports:
      - '80:80'
      
    # env_file:
    #   - mysql.env


    networks:
      - my-network

# 네트워크 만들기 명령어 : docker network create my-network
# 이걸 해야 외부에 있는 mysql connection을 할 수 있다.
networks:
  my-network:
    driver: bridge